### ISSUE TITLE
Requirement Gathering

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/tbr5#1]
- [ ] #2 Do Field visits and share findings
- [ ] #3 Identify Codebook forms and variables 
- [ ] #4 Identify Reporting indicators
- [ ] #5 Identify Users, roles, privileges
- [ ] #6 Create Basic Mockups
- [ ] #7 Compile statement of work and finalize scope

**Comment by maina** [comment]
test slack notifications
