### ISSUE TITLE
Design mockups for TB app for mobile, tablet, and web forms

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/tbr5#12]
Design mockups for TB app for following

- [ ] #26 Design mockups for mobile app forms
- [ ] #27 Design mockups for tablet app forms
- [ ] #28 Design mockups for web app forms #
