### ISSUE TITLE
Design mockups for TB app web dashboard

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/tbr5#13]
Design mockups specific to TB app web dashboard. It should include 

- [ ] #29 Design mockups for Admin panel for TB specific app
- [ ] #30 Design mockups for Team management panel
- [ ] #31 Design mockups for Screening panel
- [ ] #32 Design mockups for Patient panel
- [ ] #33 Design mockups for Diagnosis, Tests and Test Results panel
- [ ] #34 Design mockups for Treatment and Followup panel
- [ ] #35 Design mockups for Drugs managment panel
- [ ] #36 Design mockups for End of Treatment panel
