### ISSUE TITLE
Design and plan web dashboard for team management

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/tbr5#15]
A TB application requires community and faciility based teams which work on different locations, under different managers in teams with hierarchical model.

TMM should provide functionality mentioned in document here https://wiki.openmrs.org/display/docs/Team+Management+Module+Redesign+-+TMM-2.x.x

- [ ] opensrp/openmrs-module-team#9 Team Hierarchy UI
- [ ] opensrp/openmrs-module-team#13 Team UI
- [ ] opensrp/openmrs-module-team#17 Team Member UI
- [ ] opensrp/openmrs-module-team#21 Team Logs UI
- [ ] opensrp/openmrs-module-team#34 Tree data for Team Role hierarchy
- [ ] opensrp/openmrs-module-team#35 Tree data for Team Hierarchy
- [ ] opensrp/openmrs-module-team#33 All data access should be protected by permissions
- [ ] opensrp/openmrs-module-team#25 Documentation for TMM updated version
- [ ] opensrp/openmrs-module-team#24 Bug fixing and final release for deployment
