### ISSUE TITLE
System Analysis and Design [includes planning]

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/tbr5#8]
Thoroughly analyze the requirements and design modules and plan next activities

- [ ] #9 Hold design workshop to bring partners onboard
- [ ] #10 Share and assess the information collected during requirement gathering
- [ ] #11 Create and evaluate the plan for next steps and goals
- [ ] #12 Design mockups for TB app mobile, tablet, and web forms
- [ ] #13 Design mockups for TB app admin dashboard
- [ ] #14 Design mockups for TB app reporting dashboard
- [ ] #15 Design and plan web dashboard for team management
- [ ] #44 Design and plan user configurable application
- [ ] #20 Design and plan web dashboard for admin
- [ ] #21 Design and plan web dashboard for reporting
- [ ] #22 Design and plan TB specific application
- [ ] #23 Design and plan application installer
- [ ] #24 Design and plan mobile app performance monitoring
- [ ] #25 Design and plan web app performance monitoring
